#############################################################################
# Makefile for building: cuACS
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  cuACS.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile cuACS.pro -spec linux-g++ CONFIG+=qml_debug CONFIG+=force_debug_info CONFIG+=separate_debug_info
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cuACS1.0.0
DISTDIR = /home/student/Documents/COMP3004/cuACS/.tmp/cuACS1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lsqlite3 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = data/DatabaseController.cpp \
		interface/main.cpp \
		interface/MainWindow.cpp \
		interface/AnimalInputDiag.cpp \
		interface/AnimalListView.cpp \
		interface/AnimalDetailDiag.cpp \
		interface/ClientProfile.cpp \
		interface/ClientInputDiag.cpp \
		interface/ClientListView.cpp \
		interface/ClientDetailDiag.cpp \
		interface/mytablewidgetitem.cpp \
		interface/ArrayCollection.cpp \
		interface/Entity.cpp \
		interface/EntityBuilder.cpp \
		interface/CUACSController.cpp \
		interface/ACMController.cpp \
		interface/AnimalClientPair.cpp \
		interface/AttributeComparator.cpp \
		interface/CandidateSet.cpp \
		interface/DecisionTreeDataItem.cpp \
		interface/OptimizedDecisionTree.cpp \
		interface/Tests.cpp \
		interface/ACMTreeController.cpp \
		interface/QuestionnaireDialog.cpp \
		interface/LoginDialog.cpp \
		interface/ACMListView.cpp \
		interface/ACMDetailDialog.cpp moc_MainWindow.cpp \
		moc_AnimalInputDiag.cpp \
		moc_AnimalListView.cpp \
		moc_AnimalDetailDiag.cpp \
		moc_ClientInputDiag.cpp \
		moc_ClientListView.cpp \
		moc_ClientDetailDiag.cpp \
		moc_QuestionnaireDialog.cpp \
		moc_LoginDialog.cpp \
		moc_ACMListView.cpp \
		moc_ACMDetailDialog.cpp
OBJECTS       = DatabaseController.o \
		main.o \
		MainWindow.o \
		AnimalInputDiag.o \
		AnimalListView.o \
		AnimalDetailDiag.o \
		ClientProfile.o \
		ClientInputDiag.o \
		ClientListView.o \
		ClientDetailDiag.o \
		mytablewidgetitem.o \
		ArrayCollection.o \
		Entity.o \
		EntityBuilder.o \
		CUACSController.o \
		ACMController.o \
		AnimalClientPair.o \
		AttributeComparator.o \
		CandidateSet.o \
		DecisionTreeDataItem.o \
		OptimizedDecisionTree.o \
		Tests.o \
		ACMTreeController.o \
		QuestionnaireDialog.o \
		LoginDialog.o \
		ACMListView.o \
		ACMDetailDialog.o \
		moc_MainWindow.o \
		moc_AnimalInputDiag.o \
		moc_AnimalListView.o \
		moc_AnimalDetailDiag.o \
		moc_ClientInputDiag.o \
		moc_ClientListView.o \
		moc_ClientDetailDiag.o \
		moc_QuestionnaireDialog.o \
		moc_LoginDialog.o \
		moc_ACMListView.o \
		moc_ACMDetailDialog.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_target.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/separate_debug_info.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuACS.pro data/DatabaseController.h \
		interface/MainWindow.h \
		interface/AnimalInputDiag.h \
		interface/AnimalListView.h \
		interface/AnimalDetailDiag.h \
		interface/ClientProfile.h \
		interface/Levels.h \
		interface/ClientInputDiag.h \
		interface/ClientListView.h \
		interface/ClientDetailDiag.h \
		interface/mytablewidgetitem.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/EntityBuilder.h \
		interface/CUACSController.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/AttributeComparator.h \
		interface/CandidateSet.h \
		interface/DecisionTreeDataItem.h \
		interface/OptimizedDecisionTree.h \
		interface/Tests.h \
		interface/Attributes.h \
		interface/ACMTreeController.h \
		interface/QuestionnaireDialog.h \
		interface/Attributes.h \
		interface/LoginDialog.h \
		interface/ACMListView.h \
		interface/ACMDetailDialog.h data/DatabaseController.cpp \
		interface/main.cpp \
		interface/MainWindow.cpp \
		interface/AnimalInputDiag.cpp \
		interface/AnimalListView.cpp \
		interface/AnimalDetailDiag.cpp \
		interface/ClientProfile.cpp \
		interface/ClientInputDiag.cpp \
		interface/ClientListView.cpp \
		interface/ClientDetailDiag.cpp \
		interface/mytablewidgetitem.cpp \
		interface/ArrayCollection.cpp \
		interface/Entity.cpp \
		interface/EntityBuilder.cpp \
		interface/CUACSController.cpp \
		interface/ACMController.cpp \
		interface/AnimalClientPair.cpp \
		interface/AttributeComparator.cpp \
		interface/CandidateSet.cpp \
		interface/DecisionTreeDataItem.cpp \
		interface/OptimizedDecisionTree.cpp \
		interface/Tests.cpp \
		interface/ACMTreeController.cpp \
		interface/QuestionnaireDialog.cpp \
		interface/LoginDialog.cpp \
		interface/ACMListView.cpp \
		interface/ACMDetailDialog.cpp
QMAKE_TARGET  = cuACS
DESTDIR       = 
TARGET        = cuACS


first: all
####### Build rules

$(TARGET): ui_listview.h ui_mainwindow.h ui_animaldetaildialog.h ui_animalinputdialog.h ui_clientinputdialog.h ui_clientdetaildialog.h ui_questionnairedialog.h ui_logindialog.h ui_acmdetaildialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	objcopy --only-keep-debug cuACS cuACS.debug && objcopy --strip-debug cuACS && objcopy --add-gnu-debuglink=cuACS.debug cuACS && chmod -x cuACS.debug

Makefile: cuACS.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_target.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/separate_debug_info.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuACS.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile cuACS.pro -spec linux-g++ CONFIG+=qml_debug CONFIG+=force_debug_info CONFIG+=separate_debug_info
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_target.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/separate_debug_info.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
cuACS.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile cuACS.pro -spec linux-g++ CONFIG+=qml_debug CONFIG+=force_debug_info CONFIG+=separate_debug_info

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents data/DatabaseController.h interface/MainWindow.h interface/AnimalInputDiag.h interface/AnimalListView.h interface/AnimalDetailDiag.h interface/ClientProfile.h interface/Levels.h interface/ClientInputDiag.h interface/ClientListView.h interface/ClientDetailDiag.h interface/mytablewidgetitem.h interface/Entity.h interface/Description.h interface/ArrayCollection.h interface/AbstractCollection.h interface/EntityBuilder.h interface/CUACSController.h interface/ACMController.h interface/AnimalClientPair.h interface/AttributeComparator.h interface/CandidateSet.h interface/DecisionTreeDataItem.h interface/OptimizedDecisionTree.h interface/Tests.h interface/Attributes.h interface/ACMTreeController.h interface/QuestionnaireDialog.h interface/Attributes.h interface/LoginDialog.h interface/ACMListView.h interface/ACMDetailDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents data/DatabaseController.cpp interface/main.cpp interface/MainWindow.cpp interface/AnimalInputDiag.cpp interface/AnimalListView.cpp interface/AnimalDetailDiag.cpp interface/ClientProfile.cpp interface/ClientInputDiag.cpp interface/ClientListView.cpp interface/ClientDetailDiag.cpp interface/mytablewidgetitem.cpp interface/ArrayCollection.cpp interface/Entity.cpp interface/EntityBuilder.cpp interface/CUACSController.cpp interface/ACMController.cpp interface/AnimalClientPair.cpp interface/AttributeComparator.cpp interface/CandidateSet.cpp interface/DecisionTreeDataItem.cpp interface/OptimizedDecisionTree.cpp interface/Tests.cpp interface/ACMTreeController.cpp interface/QuestionnaireDialog.cpp interface/LoginDialog.cpp interface/ACMListView.cpp interface/ACMDetailDialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents interface/listview.ui interface/mainwindow.ui interface/animaldetaildialog.ui interface/animalinputdialog.ui interface/clientinputdialog.ui interface/clientdetaildialog.ui interface/questionnairedialog.ui interface/logindialog.ui interface/acmdetaildialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/student/Documents/COMP3004/cuACS/cuACS.debug .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -g -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWindow.cpp moc_AnimalInputDiag.cpp moc_AnimalListView.cpp moc_AnimalDetailDiag.cpp moc_ClientInputDiag.cpp moc_ClientListView.cpp moc_ClientDetailDiag.cpp moc_QuestionnaireDialog.cpp moc_LoginDialog.cpp moc_ACMListView.cpp moc_ACMDetailDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_AnimalInputDiag.cpp moc_AnimalListView.cpp moc_AnimalDetailDiag.cpp moc_ClientInputDiag.cpp moc_ClientListView.cpp moc_ClientDetailDiag.cpp moc_QuestionnaireDialog.cpp moc_LoginDialog.cpp moc_ACMListView.cpp moc_ACMDetailDialog.cpp
moc_MainWindow.cpp: interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/MainWindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/MainWindow.h -o moc_MainWindow.cpp

moc_AnimalInputDiag.cpp: interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/AnimalInputDiag.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/AnimalInputDiag.h -o moc_AnimalInputDiag.cpp

moc_AnimalListView.cpp: interface/mytablewidgetitem.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/AnimalDetailDiag.h \
		interface/AnimalListView.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/AnimalListView.h -o moc_AnimalListView.cpp

moc_AnimalDetailDiag.cpp: interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/AnimalDetailDiag.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/AnimalDetailDiag.h -o moc_AnimalDetailDiag.cpp

moc_ClientInputDiag.cpp: interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/ClientInputDiag.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/ClientInputDiag.h -o moc_ClientInputDiag.cpp

moc_ClientListView.cpp: interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/ClientDetailDiag.h \
		interface/QuestionnaireDialog.h \
		interface/ClientListView.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/ClientListView.h -o moc_ClientListView.cpp

moc_ClientDetailDiag.cpp: interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/QuestionnaireDialog.h \
		interface/ClientDetailDiag.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/ClientDetailDiag.h -o moc_ClientDetailDiag.cpp

moc_QuestionnaireDialog.cpp: interface/Attributes.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/QuestionnaireDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/QuestionnaireDialog.h -o moc_QuestionnaireDialog.cpp

moc_LoginDialog.cpp: interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/LoginDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/LoginDialog.h -o moc_LoginDialog.cpp

moc_ACMListView.cpp: interface/mytablewidgetitem.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/ACMListView.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/ACMListView.h -o moc_ACMListView.cpp

moc_ACMDetailDialog.cpp: interface/AnimalClientPair.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/ACMController.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/ACMDetailDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/COMP3004/cuACS -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include interface/ACMDetailDialog.h -o moc_ACMDetailDialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_listview.h ui_mainwindow.h ui_animaldetaildialog.h ui_animalinputdialog.h ui_clientinputdialog.h ui_clientdetaildialog.h ui_questionnairedialog.h ui_logindialog.h ui_acmdetaildialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_listview.h ui_mainwindow.h ui_animaldetaildialog.h ui_animalinputdialog.h ui_clientinputdialog.h ui_clientdetaildialog.h ui_questionnairedialog.h ui_logindialog.h ui_acmdetaildialog.h
ui_listview.h: interface/listview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic interface/listview.ui -o ui_listview.h

ui_mainwindow.h: interface/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic interface/mainwindow.ui -o ui_mainwindow.h

ui_animaldetaildialog.h: interface/animaldetaildialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic interface/animaldetaildialog.ui -o ui_animaldetaildialog.h

ui_animalinputdialog.h: interface/animalinputdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic interface/animalinputdialog.ui -o ui_animalinputdialog.h

ui_clientinputdialog.h: interface/clientinputdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic interface/clientinputdialog.ui -o ui_clientinputdialog.h

ui_clientdetaildialog.h: interface/clientdetaildialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic interface/clientdetaildialog.ui -o ui_clientdetaildialog.h

ui_questionnairedialog.h: interface/questionnairedialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic interface/questionnairedialog.ui -o ui_questionnairedialog.h

ui_logindialog.h: interface/logindialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic interface/logindialog.ui -o ui_logindialog.h

ui_acmdetaildialog.h: interface/acmdetaildialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic interface/acmdetaildialog.ui -o ui_acmdetaildialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

DatabaseController.o: data/DatabaseController.cpp data/DatabaseController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DatabaseController.o data/DatabaseController.cpp

main.o: interface/main.cpp interface/MainWindow.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o interface/main.cpp

MainWindow.o: interface/MainWindow.cpp interface/MainWindow.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		ui_mainwindow.h \
		interface/Tests.h \
		interface/AnimalInputDiag.h \
		interface/ClientInputDiag.h \
		interface/AnimalListView.h \
		interface/mytablewidgetitem.h \
		interface/AnimalDetailDiag.h \
		interface/ClientListView.h \
		interface/ClientDetailDiag.h \
		interface/QuestionnaireDialog.h \
		interface/ACMListView.h \
		interface/LoginDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o interface/MainWindow.cpp

AnimalInputDiag.o: interface/AnimalInputDiag.cpp interface/AnimalInputDiag.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		ui_animalinputdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalInputDiag.o interface/AnimalInputDiag.cpp

AnimalListView.o: interface/AnimalListView.cpp interface/AnimalListView.h \
		interface/mytablewidgetitem.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/AnimalDetailDiag.h \
		ui_listview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalListView.o interface/AnimalListView.cpp

AnimalDetailDiag.o: interface/AnimalDetailDiag.cpp interface/AnimalDetailDiag.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		ui_animaldetaildialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalDetailDiag.o interface/AnimalDetailDiag.cpp

ClientProfile.o: interface/ClientProfile.cpp interface/ClientProfile.h \
		interface/Levels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClientProfile.o interface/ClientProfile.cpp

ClientInputDiag.o: interface/ClientInputDiag.cpp interface/ClientInputDiag.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		ui_clientinputdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClientInputDiag.o interface/ClientInputDiag.cpp

ClientListView.o: interface/ClientListView.cpp interface/ClientListView.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/ClientDetailDiag.h \
		interface/QuestionnaireDialog.h \
		ui_listview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClientListView.o interface/ClientListView.cpp

ClientDetailDiag.o: interface/ClientDetailDiag.cpp interface/ClientDetailDiag.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		interface/QuestionnaireDialog.h \
		ui_clientdetaildialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClientDetailDiag.o interface/ClientDetailDiag.cpp

mytablewidgetitem.o: interface/mytablewidgetitem.cpp interface/mytablewidgetitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mytablewidgetitem.o interface/mytablewidgetitem.cpp

ArrayCollection.o: interface/ArrayCollection.cpp interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/Description.h \
		interface/Entity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ArrayCollection.o interface/ArrayCollection.cpp

Entity.o: interface/Entity.cpp interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Entity.o interface/Entity.cpp

EntityBuilder.o: interface/EntityBuilder.cpp interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EntityBuilder.o interface/EntityBuilder.cpp

CUACSController.o: interface/CUACSController.cpp interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CUACSController.o interface/CUACSController.cpp

ACMController.o: interface/ACMController.cpp interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/CandidateSet.h \
		interface/ACMTreeController.h \
		interface/OptimizedDecisionTree.h \
		interface/DecisionTreeDataItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ACMController.o interface/ACMController.cpp

AnimalClientPair.o: interface/AnimalClientPair.cpp interface/AnimalClientPair.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/AttributeComparator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalClientPair.o interface/AnimalClientPair.cpp

AttributeComparator.o: interface/AttributeComparator.cpp interface/AttributeComparator.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/Attributes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AttributeComparator.o interface/AttributeComparator.cpp

CandidateSet.o: interface/CandidateSet.cpp interface/CandidateSet.h \
		interface/AnimalClientPair.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CandidateSet.o interface/CandidateSet.cpp

DecisionTreeDataItem.o: interface/DecisionTreeDataItem.cpp interface/DecisionTreeDataItem.h \
		interface/CandidateSet.h \
		interface/AnimalClientPair.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DecisionTreeDataItem.o interface/DecisionTreeDataItem.cpp

OptimizedDecisionTree.o: interface/OptimizedDecisionTree.cpp interface/OptimizedDecisionTree.h \
		interface/CandidateSet.h \
		interface/AnimalClientPair.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/DecisionTreeDataItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OptimizedDecisionTree.o interface/OptimizedDecisionTree.cpp

Tests.o: interface/Tests.cpp interface/Tests.h \
		interface/MainWindow.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tests.o interface/Tests.cpp

ACMTreeController.o: interface/ACMTreeController.cpp interface/ACMTreeController.h \
		interface/OptimizedDecisionTree.h \
		interface/CandidateSet.h \
		interface/AnimalClientPair.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/DecisionTreeDataItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ACMTreeController.o interface/ACMTreeController.cpp

QuestionnaireDialog.o: interface/QuestionnaireDialog.cpp interface/QuestionnaireDialog.h \
		interface/Attributes.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		ui_questionnairedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QuestionnaireDialog.o interface/QuestionnaireDialog.cpp

LoginDialog.o: interface/LoginDialog.cpp interface/LoginDialog.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		ui_logindialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoginDialog.o interface/LoginDialog.cpp

ACMListView.o: interface/ACMListView.cpp interface/ACMListView.h \
		interface/mytablewidgetitem.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/ACMController.h \
		interface/AnimalClientPair.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		ui_listview.h \
		interface/ACMDetailDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ACMListView.o interface/ACMListView.cpp

ACMDetailDialog.o: interface/ACMDetailDialog.cpp interface/ACMDetailDialog.h \
		interface/AnimalClientPair.h \
		interface/EntityBuilder.h \
		interface/Entity.h \
		interface/Description.h \
		interface/ArrayCollection.h \
		interface/AbstractCollection.h \
		interface/CUACSController.h \
		data/DatabaseController.h \
		interface/ACMController.h \
		interface/CandidateSet.h \
		interface/Attributes.h \
		ui_acmdetaildialog.h \
		interface/AnimalDetailDiag.h \
		interface/ClientDetailDiag.h \
		interface/QuestionnaireDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ACMDetailDialog.o interface/ACMDetailDialog.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_AnimalInputDiag.o: moc_AnimalInputDiag.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AnimalInputDiag.o moc_AnimalInputDiag.cpp

moc_AnimalListView.o: moc_AnimalListView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AnimalListView.o moc_AnimalListView.cpp

moc_AnimalDetailDiag.o: moc_AnimalDetailDiag.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AnimalDetailDiag.o moc_AnimalDetailDiag.cpp

moc_ClientInputDiag.o: moc_ClientInputDiag.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClientInputDiag.o moc_ClientInputDiag.cpp

moc_ClientListView.o: moc_ClientListView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClientListView.o moc_ClientListView.cpp

moc_ClientDetailDiag.o: moc_ClientDetailDiag.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClientDetailDiag.o moc_ClientDetailDiag.cpp

moc_QuestionnaireDialog.o: moc_QuestionnaireDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QuestionnaireDialog.o moc_QuestionnaireDialog.cpp

moc_LoginDialog.o: moc_LoginDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoginDialog.o moc_LoginDialog.cpp

moc_ACMListView.o: moc_ACMListView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ACMListView.o moc_ACMListView.cpp

moc_ACMDetailDialog.o: moc_ACMDetailDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ACMDetailDialog.o moc_ACMDetailDialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

