#ifndef ATTRIBUTES_H
#define ATTRIBUTES_H

enum class AnimalAttribute : int
{
    ID = 0,
    NAME = 1,
    SPECIES = 2,
    BREED = 3,
    AGE = 4,
    LIFE_EXPECTANCY = 5,
    SEX = 6,
    IMMUNIZED = 7,
    LEVEL_OF_CARE = 8,
    LEVEL_OF_ENERGY = 9,
    TRAINING_LEVEL = 10,
    TRAINABILITY_LEVEL = 11,
    AFFINITY_FOR_PEOPLE = 12,
    AFFINITY_FOR_CHILDREN = 13,
    AFFINITY_FOR_ANIMALS = 14,
    APPROACHABILITY = 15,
    TIME_COMMITMENT = 16,
    DIET_NEEDS = 17,
    MOBILITY_NEEDS = 18,
    DISABILITY_NEEDS = 19,
    ABUSE_HISTORY = 20,
    BIOGRAPHY = 21
};

enum class ClientAttribute : int
{
    ID = 0,
    FIRST_NAME = 1,
    HAS_CHILDREN_UNDER_TWELVE = 2,
    HAS_PETS = 3,
    AGE = 4,
    LAST_NAME = 5,
    PREF_TITLE = 6,
    PHONE_NUMBER = 7,
    STREET_LINE_1 = 8,
    STREET_LINE_2 = 9,
    CITY = 10,
    SUBNATIONAL_DIVISION = 11,
    COUNTRY = 12,
    POSTAL_CODE = 13,
    LENGTH_OF_OWNERSHIP_EXPECTATION = 14,
    MONTHLY_BUDGET_FOR_ANIMAL = 15,
    AVAILABILITY_PER_DAY = 16,
    LEVEL_OF_MOBILITY = 17,
    LEVEL_OF_PATIENCE = 18,
    PREVIOUS_EXPERIENCE = 19,
    PHYSICAL_AFFECTION = 20,
};

#endif // ATTRIBUTES_H
